/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRecorrentesRouteImport } from './routes/_authenticated/recorrentes'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsumoRouteImport } from './routes/_authenticated/consumo'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAssinaturasRouteImport } from './routes/_authenticated/assinaturas'
import { Route as AuthenticatedDespesasIndexRouteImport } from './routes/_authenticated/despesas.index'
import { Route as AuthenticatedDespesasNovaRouteImport } from './routes/_authenticated/despesas.nova'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecorrentesRoute =
  AuthenticatedRecorrentesRouteImport.update({
    id: '/recorrentes',
    path: '/recorrentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsumoRoute = AuthenticatedConsumoRouteImport.update({
  id: '/consumo',
  path: '/consumo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturasRoute =
  AuthenticatedAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDespesasIndexRoute =
  AuthenticatedDespesasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDespesasRoute,
  } as any)
const AuthenticatedDespesasNovaRoute =
  AuthenticatedDespesasNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedDespesasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/chat': typeof AuthenticatedChatRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consumo': typeof AuthenticatedConsumoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/despesas': typeof AuthenticatedDespesasRouteWithChildren
  '/insights': typeof AuthenticatedInsightsRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/recorrentes': typeof AuthenticatedRecorrentesRoute
  '/despesas/nova': typeof AuthenticatedDespesasNovaRoute
  '/despesas/': typeof AuthenticatedDespesasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/chat': typeof AuthenticatedChatRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consumo': typeof AuthenticatedConsumoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/recorrentes': typeof AuthenticatedRecorrentesRoute
  '/despesas/nova': typeof AuthenticatedDespesasNovaRoute
  '/despesas': typeof AuthenticatedDespesasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/consumo': typeof AuthenticatedConsumoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRouteWithChildren
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/recorrentes': typeof AuthenticatedRecorrentesRoute
  '/_authenticated/despesas/nova': typeof AuthenticatedDespesasNovaRoute
  '/_authenticated/despesas/': typeof AuthenticatedDespesasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/assinaturas'
    | '/chat'
    | '/configuracoes'
    | '/consumo'
    | '/dashboard'
    | '/despesas'
    | '/insights'
    | '/produtos'
    | '/recorrentes'
    | '/despesas/nova'
    | '/despesas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/assinaturas'
    | '/chat'
    | '/configuracoes'
    | '/consumo'
    | '/dashboard'
    | '/insights'
    | '/produtos'
    | '/recorrentes'
    | '/despesas/nova'
    | '/despesas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/assinaturas'
    | '/_authenticated/chat'
    | '/_authenticated/configuracoes'
    | '/_authenticated/consumo'
    | '/_authenticated/dashboard'
    | '/_authenticated/despesas'
    | '/_authenticated/insights'
    | '/_authenticated/produtos'
    | '/_authenticated/recorrentes'
    | '/_authenticated/despesas/nova'
    | '/_authenticated/despesas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recorrentes': {
      id: '/_authenticated/recorrentes'
      path: '/recorrentes'
      fullPath: '/recorrentes'
      preLoaderRoute: typeof AuthenticatedRecorrentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consumo': {
      id: '/_authenticated/consumo'
      path: '/consumo'
      fullPath: '/consumo'
      preLoaderRoute: typeof AuthenticatedConsumoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinaturas': {
      id: '/_authenticated/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AuthenticatedAssinaturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas/': {
      id: '/_authenticated/despesas/'
      path: '/'
      fullPath: '/despesas/'
      preLoaderRoute: typeof AuthenticatedDespesasIndexRouteImport
      parentRoute: typeof AuthenticatedDespesasRoute
    }
    '/_authenticated/despesas/nova': {
      id: '/_authenticated/despesas/nova'
      path: '/nova'
      fullPath: '/despesas/nova'
      preLoaderRoute: typeof AuthenticatedDespesasNovaRouteImport
      parentRoute: typeof AuthenticatedDespesasRoute
    }
  }
}

interface AuthenticatedDespesasRouteChildren {
  AuthenticatedDespesasNovaRoute: typeof AuthenticatedDespesasNovaRoute
  AuthenticatedDespesasIndexRoute: typeof AuthenticatedDespesasIndexRoute
}

const AuthenticatedDespesasRouteChildren: AuthenticatedDespesasRouteChildren = {
  AuthenticatedDespesasNovaRoute: AuthenticatedDespesasNovaRoute,
  AuthenticatedDespesasIndexRoute: AuthenticatedDespesasIndexRoute,
}

const AuthenticatedDespesasRouteWithChildren =
  AuthenticatedDespesasRoute._addFileChildren(
    AuthenticatedDespesasRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssinaturasRoute: typeof AuthenticatedAssinaturasRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConsumoRoute: typeof AuthenticatedConsumoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRouteWithChildren
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRecorrentesRoute: typeof AuthenticatedRecorrentesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssinaturasRoute: AuthenticatedAssinaturasRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConsumoRoute: AuthenticatedConsumoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRouteWithChildren,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRecorrentesRoute: AuthenticatedRecorrentesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
